spring:
  datasource:
#    url: jdbc:mysql://localhost/android?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password:
    url: jdbc:mysql://120.79.18.242/android?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: lilinhai123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      auto-commit: true
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: update
      #控制台显示SQL
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    context-path: /sharePark
  port: 8080


